### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by pavelenzi** [disconnectme/disconnect.me#4]
There is a spelling error in the section About Us:

About Us
Our mission is to help people understand and Control Their online dating.
Why Disconnect?
Because your staff info Should be yours. But today Thousands of companies invisibly collect your data online, treats including  >>>>>browisng<<<<<< and your search history, local, data, and social connections. Often staff This info is packaged and sold without your permission

**Comment by oldestlivingboy** [comment]
Thanks!
